### ISSUE TITLE
Adaguc viewer error on large WMS GetCapabilities XML responses

### ISSUE THREAD

**Issue by alexandreleroux** [KNMI/adaguc-viewer#42]
Hi and thanks for the Adaguc Viewer.

Issue:
* Adaguc Viewer generates an error when trying to load a large WMS GetCapabilities XML
* Example of a large WMS GetCapabilities XML: https://geo.weather.gc.ca/geomet?lang=en&service=WMS&version=1.3.0&request=GetCapabilities
* Corresponding Adaguc error (tested with [this Adaguc viewer](http://meteocentre.com/plus/)): 
```
Cannot connect to WMS service.
Unable to do getcapabilities for:
webmapjs/php/xml2jsonrequest.php?request=http%3A%2F%2Fgeo.weather.gc.ca%2Fgeomet%2F%3Flang%3DE%26service%3DWMS%26request%3DGetCapabilities
Result:
[object Object]
```

The same Adaguc viewer does properly load smaller WMS GetCapabilities XMLs from the same WMS server, example: https://geo.weather.gc.ca/geomet?service=WMS&version=1.3.0&request=GetCapabilities&layer=RADAR_1KM_RSNO is loaded and displayed properly by Adaguc.

Anything that can be done to increase the maximum size of a WMS GetCapabilities XML supported by the Adaguc viewer? Thanks!

**Comment by maartenplieger** [comment]
Hi Alexandre, we will check it out!

**Comment by alexandreleroux** [comment]
Thanks @maartenplieger . The owner of the Adaguc installation that generated the error associated with this ticket made changes to his Adaguc server and it now seems to work fine.

I unfortunately don't know what makes Adaguc work now with our unusually large WMS GetCapabilities XML, but it's still good news nonetheless. Closing the ticket, thanks!
