### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by SarahG-579462** [KNMI/adaguc-viewer#46]
Hi, I'm looking into web mapping technologies and found this one, but there is no license information included in the repo. Is it the same as the server, adaguc-server, Apache v2.0? Could it be included in the base directory?

**Comment by maartenplieger** [comment]
Thanks for reporting! We will add it. 

Please note that we do not work on adaguc-viewer at the moment. We work on adaguc-server and https://opengeoweb.com/

There is ambition to revive adaguc-viewer with opengeoweb components in the future.

**Comment by maartenplieger** [comment]
Added the GPL license to the main part. Please note that the webmapjs part itself has the Apache license (in https://github.com/KNMI/adaguc-viewer/tree/master/webmapjs)

**Comment by SarahG-579462** [comment]
Thank you Maarten, I'll check out your new project!
